[package]
name = "folders"
version = "0.1.0"
edition = "2021"
exclude = ["/example"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
serde_yaml = "0.9.23"
